package com.sphynxs.mydatabases.ui.screens.queryeditor.components

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.AnnotatedString
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * TDD tests for BracketHighlightTransformation (BR-1).
 *
 * Tests bracket pair highlighting visual transformation:
 * - Highlights both bracket offsets with background color
 * - No highlight when bracketPair is null
 *
 * @author israel-icm (generated by SDD apply phase)
 * @date 2026-06-29
 */
class BracketHighlightTransformationTest {

    /**
     * Task 4.3.5 — TDD RED
     * Cursor adjacent to bracket → highlights both offsets with background
     */
    @Test
    fun `filter_cursorAdjacentToBracket_highlightsBothOffsets`() {
        // GIVEN
        val text = AnnotatedString("SELECT (a + b)")
        val bracketPair = Pair(7, 13) // offsets of '(' and ')'
        val transformation = BracketHighlightTransformation(bracketPair, Color.Yellow)

        // WHEN
        val result = transformation.filter(text)

        // THEN: Both bracket positions should have background style
        val spans = result.text.spanStyles
        val highlightedOffsets = spans.map { it.start }.toSet()
        assertTrue("Should highlight offset 7", 7 in highlightedOffsets)
        assertTrue("Should highlight offset 13", 13 in highlightedOffsets)
        
        // Both should have the same background color
        spans.forEach { span ->
            assertEquals(Color.Yellow, span.item.background)
        }
    }

    /**
     * Task 4.3.5 — TDD RED (TRIANGULATE)
     * No bracket pair → no highlighting
     */
    @Test
    fun `filter_noBracketPair_noHighlight`() {
        // GIVEN
        val text = AnnotatedString("SELECT (a + b)")
        val transformation = BracketHighlightTransformation(null, Color.Yellow)

        // WHEN
        val result = transformation.filter(text)

        // THEN: No spans should be added
        assertEquals(0, result.text.spanStyles.size)
    }
}
