package com.sphynxs.mydatabases.ui.screens.queryeditor.components

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.AnnotatedString
import androidx.compose.ui.text.SpanStyle
import androidx.compose.ui.text.buildAnnotatedString
import androidx.compose.ui.text.input.OffsetMapping
import androidx.compose.ui.text.input.TransformedText
import androidx.compose.ui.text.input.VisualTransformation
import androidx.compose.ui.text.withStyle
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * TDD tests for CompositeVisualTransformation (BR-1, FR-14).
 *
 * Tests layered visual transformations:
 * - Merge AnnotatedString span styles from multiple layers
 * - OffsetMapping delegation
 *
 * Follows Phase 4.3 design: chain transformations for syntax + brackets + matches.
 *
 * @author israel-icm (generated by SDD apply phase)
 * @date 2026-06-29
 */
class CompositeVisualTransformationTest {

    /**
     * Task 4.3.1 — TDD RED
     * Merge span styles from two layers
     */
    @Test
    fun `filter_twoLayers_mergesSpanStyles`() {
        // GIVEN: Layer 1 adds blue text, Layer 2 adds yellow background
        val layer1 = VisualTransformation { text ->
            TransformedText(
                text = buildAnnotatedString {
                    append(text.text)
                    addStyle(SpanStyle(color = Color.Blue), 0, 6)
                },
                offsetMapping = OffsetMapping.Identity
            )
        }
        
        val layer2 = VisualTransformation { text ->
            TransformedText(
                text = buildAnnotatedString {
                    append(text.text)
                    addStyle(SpanStyle(background = Color.Yellow), 0, 6)
                },
                offsetMapping = OffsetMapping.Identity
            )
        }
        
        val composite = CompositeVisualTransformation(listOf(layer1, layer2))
        val input = AnnotatedString("SELECT")

        // WHEN
        val result = composite.filter(input)

        // THEN: Output should have BOTH styles
        val spans = result.text.spanStyles
        assertEquals(2, spans.size)
        assertTrue(spans.any { it.item.color == Color.Blue })
        assertTrue(spans.any { it.item.background == Color.Yellow })
    }

    /**
     * Task 4.3.3 — TDD RED (TRIANGULATE)
     * OffsetMapping returns Identity when all layers use Identity
     */
    @Test
    fun `offsetMapping_allIdentity_returnsIdentity`() {
        // GIVEN: Both layers use Identity mapping
        val layer1 = VisualTransformation { text ->
            TransformedText(
                text = buildAnnotatedString { append(text.text) },
                offsetMapping = OffsetMapping.Identity
            )
        }
        
        val layer2 = VisualTransformation { text ->
            TransformedText(
                text = buildAnnotatedString { append(text.text) },
                offsetMapping = OffsetMapping.Identity
            )
        }
        
        val composite = CompositeVisualTransformation(listOf(layer1, layer2))
        val input = AnnotatedString("SELECT")

        // WHEN
        val result = composite.filter(input)

        // THEN: Offset mapping should be Identity
        assertEquals(OffsetMapping.Identity, result.offsetMapping)
    }
}
