package com.sphynxs.mydatabases.ui.screens.queryeditor

import org.junit.Assert.assertEquals
import org.junit.Test

/**
 * TDD tests for QueryEditorViewModel bracket highlighting state (BR-1).
 *
 * Tests reactive state flow for bracket pair at cursor:
 * - Cursor adjacent to bracket → emits Pair(openOffset, closeOffset)
 * - Cursor not adjacent → emits null
 * - Debounced with tokenizer stream
 *
 * Follows Phase 4.2 design: reuse existing tokenizer flow, add bracket pair computation.
 *
 * @author israel-icm (generated by SDD apply phase)
 * @date 2026-06-29
 */
class QueryEditorViewModelTest {

    /**
     * Task 4.2.1 — TDD RED
     * BR-1.1: cursor adjacent to open bracket → emits Pair(openOffset, closeOffset)
     * 
     * Note: This is a unit test for the bracket pair computation logic.
     * We test the pure function directly, not the full ViewModel flow.
     */
    @Test
    fun `bracketPairAtCursor_adjacent_emitsPair`() {
        // GIVEN
        val text = "SELECT (a + b)"
        val cursorOffset = 7 // after '('

        // WHEN
        val bracketPair = QueryEditorViewModel.computeBracketPairAtCursor(text, cursorOffset)

        // THEN
        assertEquals(Pair(7, 13), bracketPair)
    }

    /**
     * Task 4.2.3 — TDD RED (TRIANGULATE)
     * Cursor not adjacent to bracket → emits null
     */
    @Test
    fun `bracketPairAtCursor_notAdjacent_emitsNull`() {
        // GIVEN
        val text = "SELECT (a + b)"
        val cursorOffset = 10 // middle of identifier, not adjacent

        // WHEN
        val bracketPair = QueryEditorViewModel.computeBracketPairAtCursor(text, cursorOffset)

        // THEN
        assertEquals(null, bracketPair)
    }
}
