package com.sphynxs.mydatabases.ui.screens.queryeditor.components

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.AnnotatedString
import androidx.compose.ui.text.SpanStyle
import androidx.compose.ui.text.buildAnnotatedString
import androidx.compose.ui.text.input.OffsetMapping
import androidx.compose.ui.text.input.TransformedText
import androidx.compose.ui.text.input.VisualTransformation

/**
 * VisualTransformation that highlights matching bracket pairs.
 *
 * Task 4.3.6 — TDD GREEN: Applies background color to both bracket offsets
 * when cursor is adjacent to a bracket.
 *
 * Used by BR-1 (bracket pair highlighting).
 *
 * @param bracketPair Pair of (openOffset, closeOffset) or null if no match
 * @param backgroundColor Background color for highlights (typically MaterialTheme.colorScheme.outlineVariant)
 *
 * @author israel-icm (generated by SDD apply phase)
 * @date 2026-06-29
 */
class BracketHighlightTransformation(
    private val bracketPair: Pair<Int, Int>?,
    private val backgroundColor: Color
) : VisualTransformation {

    override fun filter(text: AnnotatedString): TransformedText {
        if (bracketPair == null) {
            return TransformedText(text, OffsetMapping.Identity)
        }

        val (openOffset, closeOffset) = bracketPair
        
        val highlightedText = buildAnnotatedString {
            append(text.text)
            
            // Highlight open bracket (single character)
            if (openOffset in text.text.indices) {
                addStyle(
                    style = SpanStyle(background = backgroundColor),
                    start = openOffset,
                    end = openOffset + 1
                )
            }
            
            // Highlight close bracket (single character)
            if (closeOffset in text.text.indices) {
                addStyle(
                    style = SpanStyle(background = backgroundColor),
                    start = closeOffset,
                    end = closeOffset + 1
                )
            }
        }

        return TransformedText(highlightedText, OffsetMapping.Identity)
    }
}
