package com.sphynxs.mydatabases.ui.screens.queryeditor.components

import androidx.compose.ui.text.AnnotatedString
import androidx.compose.ui.text.buildAnnotatedString
import androidx.compose.ui.text.input.OffsetMapping
import androidx.compose.ui.text.input.TransformedText
import androidx.compose.ui.text.input.VisualTransformation

/**
 * Composite VisualTransformation that chains multiple transformations.
 *
 * Task 4.3.2 — TDD GREEN: Implements layered transformations for:
 * - Syntax highlighting (existing)
 * - Bracket pair highlighting (BR-1)
 * - Find/Replace match highlighting (FR-14)
 *
 * Design: Chain transformations sequentially, merge AnnotatedString spans.
 * OffsetMapping: returns Identity if all layers use Identity (no text changes).
 *
 * @param layers List of transformations to apply (applied in order)
 *
 * @author israel-icm (generated by SDD apply phase)
 * @date 2026-06-29
 */
class CompositeVisualTransformation(
    private val layers: List<VisualTransformation>
) : VisualTransformation {

    override fun filter(text: AnnotatedString): TransformedText {
        if (layers.isEmpty()) {
            return TransformedText(text, OffsetMapping.Identity)
        }

        // Apply each layer and collect all their transformations
        val transformedResults = layers.map { layer -> layer.filter(text) }
        
        // Merge all span styles from all layers
        val mergedText = buildAnnotatedString {
            append(text.text)
            
            // Apply all span styles from all layers
            transformedResults.forEach { result ->
                result.text.spanStyles.forEach { spanStyle ->
                    addStyle(spanStyle.item, spanStyle.start, spanStyle.end)
                }
            }
        }

        // If all layers use Identity mapping, return Identity
        val allIdentity = transformedResults.all { it.offsetMapping == OffsetMapping.Identity }
        val finalOffsetMapping = if (allIdentity) {
            OffsetMapping.Identity
        } else {
            // For now, we only support Identity mappings since we're only adding styles
            // not changing text content. If a non-Identity mapping is present, use the first one.
            transformedResults.firstOrNull { it.offsetMapping != OffsetMapping.Identity }?.offsetMapping
                ?: OffsetMapping.Identity
        }

        return TransformedText(mergedText, finalOffsetMapping)
    }
}
