package com.sphynxs.mydatabases.domain.editor

import com.sphynxs.mydatabases.ui.screens.queryeditor.components.SqlToken
import com.sphynxs.mydatabases.ui.screens.queryeditor.components.TokenKind

/**
 * Pure JVM bracket matching engine (no Android deps).
 *
 * Implements ADR-4: token walk with depth counter, handles nested brackets,
 * skips brackets inside STRING/COMMENT tokens.
 *
 * Handles six pairs: (), [], {}, '', "", ``
 *
 * Used by BR-1 (highlight), BR-2 (jump to match), BR-7 (graceful failure).
 *
 * @author israel-icm (generated by SDD apply phase)
 * @date 2026-06-29
 */
object BracketMatcher {

    private val OPEN_BRACKETS = setOf('(', '[', '{', '\'', '"', '`')
    private val CLOSE_BRACKETS = setOf(')', ']', '}', '\'', '"', '`')
    
    private fun getMatchingBracket(char: Char): Char = when (char) {
        '(' -> ')'
        ')' -> '('
        '[' -> ']'
        ']' -> '['
        '{' -> '}'
        '}' -> '{'
        '\'' -> '\''
        '"' -> '"'
        '`' -> '`'
        else -> char
    }
    
    private fun isOpenBracket(char: Char): Boolean = char in OPEN_BRACKETS
    private fun isCloseBracket(char: Char): Boolean = char in CLOSE_BRACKETS

    /**
     * Find the matching bracket offset for the bracket at/near cursorOffset.
     *
     * @param text Source SQL text
     * @param tokens Tokenized SQL (from SqlTokenizer)
     * @param cursorOffset Current cursor position
     * @return Matching bracket offset, or null if:
     *   - Cursor not adjacent to a bracket
     *   - No matching bracket (unbalanced)
     *   - Cursor inside STRING/COMMENT token
     */
    fun findMatchingBracket(
        text: String,
        tokens: List<SqlToken>,
        cursorOffset: Int
    ): Int? {
        // Task 4.1.3 — TDD GREEN: implement forward walk for '(' → ')'
        
        if (cursorOffset !in text.indices && cursorOffset - 1 !in text.indices) return null
        
        // Check character at cursor and before cursor
        val charAtCursor = if (cursorOffset in text.indices) text[cursorOffset] else null
        val charBeforeCursor = if (cursorOffset - 1 in text.indices) text[cursorOffset - 1] else null
        
        // Determine which bracket we're adjacent to
        val (bracketChar, bracketOffset) = when {
            charBeforeCursor != null && (isOpenBracket(charBeforeCursor) || isCloseBracket(charBeforeCursor)) -> 
                charBeforeCursor to (cursorOffset - 1)
            charAtCursor != null && (isOpenBracket(charAtCursor) || isCloseBracket(charAtCursor)) -> 
                charAtCursor to cursorOffset
            else -> return null
        }
        
        // Find the token containing this bracket
        val tokenAtBracket = tokens.find { bracketOffset in it.range } ?: return null
        
        // Skip if the token is STRING or COMMENT (bracket inside string/comment)
        if (tokenAtBracket.kind == TokenKind.STRING || tokenAtBracket.kind == TokenKind.COMMENT) {
            return null
        }
        
        // Only process PUNCTUATION tokens
        if (tokenAtBracket.kind != TokenKind.PUNCTUATION) return null
        
        val matchingChar = getMatchingBracket(bracketChar)
        val isForward = isOpenBracket(bracketChar)
        
        var depth = 1
        val startIndex = tokens.indexOf(tokenAtBracket)
        
        if (isForward) {
            // Forward walk for open brackets
            for (i in startIndex + 1 until tokens.size) {
                val token = tokens[i]
                
                // Only check PUNCTUATION tokens
                if (token.kind != TokenKind.PUNCTUATION) continue
                
                // Get character at this token
                val char = text.getOrNull(token.range.first) ?: continue
                
                when {
                    char == bracketChar -> depth++
                    char == matchingChar -> {
                        depth--
                        if (depth == 0) return token.range.first
                    }
                }
            }
        } else {
            // Backward walk for close brackets
            for (i in startIndex - 1 downTo 0) {
                val token = tokens[i]
                
                // Only check PUNCTUATION tokens
                if (token.kind != TokenKind.PUNCTUATION) continue
                
                // Get character at this token
                val char = text.getOrNull(token.range.first) ?: continue
                
                when {
                    char == bracketChar -> depth++
                    char == matchingChar -> {
                        depth--
                        if (depth == 0) return token.range.first
                    }
                }
            }
        }
        
        return null
    }
}
