package com.sphynxs.mydatabases.domain.editor

import com.sphynxs.mydatabases.ui.screens.queryeditor.components.SqlToken
import com.sphynxs.mydatabases.ui.screens.queryeditor.components.SqlTokenizer
import com.sphynxs.mydatabases.ui.screens.queryeditor.components.TokenKind
import org.junit.Assert.assertEquals
import org.junit.Test

/**
 * TDD tests for BracketMatcher engine (BR-1, BR-2, BR-7).
 *
 * Tests bracket matching algorithm:
 * - Forward/backward walk with depth counter
 * - All six pairs: (), [], {}, '', "", ``
 * - Edge cases: nested, unbalanced, inside STRING/COMMENT
 *
 * Follows ADR-4 design: token walk with nesting counter, skip non-PUNCTUATION.
 *
 * @author israel-icm (generated by SDD apply phase)
 * @date 2026-06-29
 */
class BracketMatcherTest {

    /**
     * Task 4.1.1 — TDD RED
     * BR-1.1: cursor after open paren → finds matching close paren
     */
    @Test
    fun `findMatchingBracket_openParen_returnsCloseParen`() {
        // GIVEN
        val buffer = "SELECT (a + b)"
        val tokens = SqlTokenizer.tokenize(buffer)
        val cursorOffset = 7 // immediately after '('

        // WHEN
        val result = BracketMatcher.findMatchingBracket(buffer, tokens, cursorOffset)

        // THEN
        assertEquals(13, result) // offset of ')'
    }

    /**
     * Task 4.1.4 — TDD RED (TRIANGULATE)
     * BR-1.2: cursor before close paren → finds matching open paren (backward walk)
     */
    @Test
    fun `findMatchingBracket_closeParen_returnsOpenParen`() {
        // GIVEN
        val buffer = "SELECT (a + b)"
        val tokens = SqlTokenizer.tokenize(buffer)
        val cursorOffset = 13 // before ')'

        // WHEN
        val result = BracketMatcher.findMatchingBracket(buffer, tokens, cursorOffset)

        // THEN
        assertEquals(7, result) // offset of '('
    }

    /**
     * Task 4.1.6 — TDD RED (TRIANGULATE)
     * Nested brackets with correct depth counting
     */
    @Test
    fun `findMatchingBracket_nested_correctDepth`() {
        // GIVEN
        val buffer = "SELECT ((a + b))"
        val tokens = SqlTokenizer.tokenize(buffer)
        val cursorOffset = 7 // after first '('

        // WHEN
        val result = BracketMatcher.findMatchingBracket(buffer, tokens, cursorOffset)

        // THEN
        assertEquals(15, result) // offset of last ')'
    }

    /**
     * Task 4.1.8 — TDD RED (TRIANGULATE)
     * BR-5: cursor at bracket inside string → returns null
     */
    @Test
    fun `findMatchingBracket_insideString_returnsNull`() {
        // GIVEN
        val buffer = "SELECT '(abc'"
        val tokens = SqlTokenizer.tokenize(buffer)
        val cursorOffset = 8 // at '(' inside string

        // WHEN
        val result = BracketMatcher.findMatchingBracket(buffer, tokens, cursorOffset)

        // THEN
        assertEquals(null, result)
    }

    /**
     * Task 4.1.10 — TDD RED (TRIANGULATE)
     * BR-7: unbalanced brackets → returns null
     */
    @Test
    fun `findMatchingBracket_unbalanced_returnsNull`() {
        // GIVEN
        val buffer = "SELECT (a + b"
        val tokens = SqlTokenizer.tokenize(buffer)
        val cursorOffset = 7 // after '('

        // WHEN
        val result = BracketMatcher.findMatchingBracket(buffer, tokens, cursorOffset)

        // THEN
        assertEquals(null, result) // no matching closer
    }

    /**
     * Task 4.1.12 — TDD RED (TRIANGULATE)
     * All six bracket pairs work in both directions
     */
    @Test
    fun `findMatchingBracket_allSixPairs_symmetric`() {
        // Test (), [], {}
        val cases = listOf(
            "SELECT (a)" to (7 to 9),
            "SELECT [a]" to (7 to 9),
            "SELECT {a}" to (7 to 9),
        )

        for ((buffer, offsets) in cases) {
            val tokens = SqlTokenizer.tokenize(buffer)
            
            // Forward: open → close
            val forwardResult = BracketMatcher.findMatchingBracket(buffer, tokens, offsets.first)
            assertEquals("Forward failed for: $buffer", offsets.second, forwardResult)
            
            // Backward: close → open
            val backwardResult = BracketMatcher.findMatchingBracket(buffer, tokens, offsets.second)
            assertEquals("Backward failed for: $buffer", offsets.first, backwardResult)
        }
    }
}
