package com.sphynxs.mydatabases.domain.editor

import android.view.KeyEvent as NativeKeyEvent
import androidx.compose.ui.input.key.KeyEvent
import com.google.common.truth.Truth.assertThat
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner

/**
 * Unit tests for EditorShortcuts.mapKeyEvent — Format shortcut mapping.
 *
 * Scope: PR #1 (SQL Formatter) only. This file intentionally covers the
 * Ctrl+Shift+F -> ShortcutAction.Format mapping (and the Ctrl+F triangulation
 * case that proves Shift is required). Other EditorShortcuts mappings
 * (Run, Save, Undo/Redo, TriggerCompletion, multi-cursor, ...) belong to
 * their own changes and are out of scope here.
 *
 * TDD RED-first workflow:
 * 1. Write failing test (scenario 10 from spec.md)
 * 2. Implement/verify minimum code to pass (EditorShortcuts.kt already maps
 *    Ctrl+Shift+F -> Format — see mapKeyEvent())
 * 3. Triangulate with the Ctrl+F (no Shift) case
 *
 * Spec: openspec/changes/editor-completion-and-format/spec.md (scenario 10)
 * Design: EditorShortcuts.kt (MODIFIED) — Ctrl+Shift+F -> ShortcutAction.Format
 *
 * NOT executed by the apply agent (maintainer runs Gradle manually). Run with:
 * ./gradlew testDebugUnitTest --tests "com.sphynxs.mydatabases.domain.editor.EditorShortcutsTest"
 *
 * @author israel-icm (generated by SDD apply phase)
 * @date 2026-07-07
 */
@RunWith(RobolectricTestRunner::class)
class EditorShortcutsTest {

    @Test
    fun `mapKeyEvent ctrlShiftF returns Format`() {
        // GIVEN a Ctrl+Shift+F key event
        val nativeEvent = NativeKeyEvent(
            0L,
            0L,
            NativeKeyEvent.ACTION_DOWN,
            NativeKeyEvent.KEYCODE_F,
            0,
            NativeKeyEvent.META_CTRL_ON or NativeKeyEvent.META_SHIFT_ON
        )
        val event = KeyEvent(nativeEvent)

        // WHEN mapped
        val action = EditorShortcuts.mapKeyEvent(event)

        // THEN it resolves to ShortcutAction.Format
        assertThat(action).isEqualTo(ShortcutAction.Format)
    }

    @Test
    fun `mapKeyEvent ctrlF without shift returns Find, not Format`() {
        // Triangulation: Ctrl+F (no Shift) must map to Find, proving the
        // Format mapping specifically requires the Shift modifier and isn't
        // accidentally satisfied by any Ctrl+F combination.
        val nativeEvent = NativeKeyEvent(
            0L,
            0L,
            NativeKeyEvent.ACTION_DOWN,
            NativeKeyEvent.KEYCODE_F,
            0,
            NativeKeyEvent.META_CTRL_ON
        )
        val event = KeyEvent(nativeEvent)

        // WHEN mapped
        val action = EditorShortcuts.mapKeyEvent(event)

        // THEN it resolves to ShortcutAction.Find (not Format)
        assertThat(action).isEqualTo(ShortcutAction.Find)
    }
}
